CREATE DATABASE IF NOT EXISTS ${MYSQL_DATABASE};

-- Usuário normal
CREATE USER IF NOT EXISTS '${MYSQL_USER}'@'%' IDENTIFIED BY '${MYSQL_PASSWORD}';
GRANT ALL PRIVILEGES ON ${MYSQL_DATABASE}.* TO '${MYSQL_USER}'@'%';

-- Usuário admin (NÃO pode conter "admin" no nome)
CREATE USER IF NOT EXISTS 'master42'@'%' IDENTIFIED BY 'masterpass';
GRANT ALL PRIVILEGES ON ${MYSQL_DATABASE}.* TO 'master42'@'%';

FLUSH PRIVILEGES;

